baseurl = "/"
contentdir = "content"
publishdir = "public"

canonifyurls = true
relativeURLS = false

theme = "hello-friend"
title = "My awesome blog"
languageCode = "en-us"
summaryLength = 42

copyright = "copyright info, like license, year, author name, etc."

# Updated Google Analytics configuration
[services]
  [services.googleAnalytics]
  id = "YOUR-GA-ID"  # Replace with your actual Google Analytics ID

# Updated author configuration
[params]
  description = "Something about your blog"
  showFooterCredits = true
  math = false
  useIcon = true
  author = "Your Name"  # Updated author field, can also use taxonomy

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"

# Taxonomy for authors (optional)
[taxonomies]
  author = "authors"  # Uncomment this if you want to use author taxonomy
