baseurl = "https://sungkweon5050.github.io/blog/"
contentdir = "content"
publishdir = "public"

canonifyurls = true
relativeURLS = false

theme = "academic"
title = "My awesome blog"
languageCode = "en-us"
summaryLength = 42